### ISSUE TITLE
Grammar formatting 

### ISSUE THREAD

**Issue by Corvious** [bmgraves/marvin#1]
https://github.com/bmgraves/marvin/blob/ae29d87f6b897ec7f19a1a743b147b910a3dcc4a/libsupport/chatty.py#L21

Should read 
db.append("*sigh* Oh Hi Marvin. How are you? No none of that? Straight to the butts... Is a simple hello too much to ask %s?" % msg.author.name)

**Comment by bmgraves** [comment]
Line has been corrected on development branch!
